### ISSUE TITLE
SRAM initialisation for LPC546XX family

### ISSUE THREAD

**Issue by allexoll** [lpc-rs/lpc-pac#54]
I'm starting to build the PACs for the (rest) LPC546XX family, but there is still an issue with needing to enable the SRAM banks. I opened an issue over at cortex-m-rt in this regard ([#303](https://github.com/rust-embedded/cortex-m-rt/issues/303) but i think that par is missing from the LPC54606-pac crate.

Have you figured out a way to include it?

**Comment by hannobraun** [comment]
I'm not sure anyone is using lpc54606-pac. I haven't done anything with it besides creating it.

**Comment by allexoll** [comment]
Ok that explains it then. I found a tweak that should work explained in [cortex-m-rt/issues/#303](https://github.com/rust-embedded/cortex-m-rt/issues/303) and i am planning to do a PR with the complete LPX546XX including this tweak if it seems OK with you.

**Comment by hannobraun** [comment]
Since you are the only user of the PAC who's involved here, I'm more than happy to accommodate you in any way that helps. The one caveat is that the PAC is hooked into [generate.sh](https://github.com/lpc-rs/lpc-pac/blob/master/generate.sh) (which I use to keep the PAC up-to-date with svd2rust), so we'd need to make sure that nothing there overwrites your changes.

But if I understand correctly, the tweak would involve adding an assembly file and somehow linking that into the build. generate.sh only overwrites the Rust code in the `src/` directory, so that shouldn't get in the way.

**Comment by allexoll** [comment]
Yes that's exactly how it works. 
We can just add "lpc54608" to generate.sh, but there will be warning in build because svd2rust v0.17.0 still generates some depreciated warnings. namely:

```
warning: lint `legacy_directory_ownership` has been removed: `converted into hard error, see issue #37872 <https://github.com/rust-lang/rust/issues/37872> for more information`
warning: lint `plugin_as_library` has been removed: `plugins have been deprecated and retired`
warning: lint `safe_extern_statics` has been removed: `converted into hard error, see issue #36247 <https://github.com/rust-lang/rust/issues/36247> for more information`
warning: unknown lint: `unions_with_drop_fields`

warning: 4 warnings emitted
```

**Comment by hannobraun** [comment]
We have these warnings in all the PACs. Not much we can do about it, until a new svd2rust version is released.
