### ISSUE TITLE
Are the checked in binaries intentional?

### ISSUE THREAD

**Issue by wt** [lpc-rs/lpc-pac#59]
I noticed two directories with binaries commited:
* lpc54608/bin/
* lpc54608/bin/

Is that intentional?

If so, when would one want to include binaries or not in a new device?

**Comment by allexoll** [comment]
The LPC546xx family boots without any SRAM bank enabled. that means you can't use the stack until they are initialized. the `/bin` folder contains the compiled `startup.s` to be included when linking, so that `cortex-m-rt` calls the `__pre_init` symbol to enable the first sram bank, allowing the use of the stack. 

At least when this was written, I tried to include this in rust but the function wrapping in rust was using the stack to push&pop registers before & after the function, crashing the execution. 

that means that yes, this code is kind of necessary to run programs on LPC546's but i have not found a better way to include it yet, but i think there was a big revamp of the cortex-m-rt since then so maybe there might be a better way.

**Comment by roblabla** [comment]
There's no way to include them in stable rust I believe. When either global asm, or naked functions + inline asm are stabilized, they could be included through those mechanism.

**Comment by allexoll** [comment]
Then we'll keep it as is until then i guess.

**Comment by allexoll** [comment]
there was a discussion about including them in the HAL instead of including them in the PAC, but since there's no HAL yet there's not much of a choice.
